### ISSUE TITLE
Rules for eslint-plugin-angular can not be found

### ISSUE THREAD

**Issue by vcernomschi** [codeclimate/codeclimate-eslint#105]
Rules for eslint-plugin-angular can not be found:

https://www.npmjs.com/package/eslint-plugin-angular

Currently I have passed pure `eslint ./` validation, but when I run 
`codeclimate analyze -f html > result.html` it doesn't found rules definition for eslint-plugin-angular. For example:

```
Definition for rule 'angular/timeout-service' was not found
```

I have codeclimate v0.35.0 and eslint v3.0.1.

**Comment by pbrisbin** [comment]
Hi @vcernomschi, sorry for the trouble. Because of security concerns with installing 3rd party dependencies as part of analysis, we only support a whitelist of shared configs and plugins.

For the `eslint-2` channel (which I assume you want to use), you can find the whitelist [here](https://github.com/codeclimate/codeclimate-eslint/blob/pb-eslint-2/package.json#L13-L23). 

Unfortunately, the angular plugin is not currently whitelisted, that's why you see this error. That said, it does appear to be a popular plugin so we'd probably be open to adding it. Let me look into that and report back.

**Comment by vcernomschi** [comment]
Thanks @pbrisbin. Does codeclimate eslint engine have some option to skip this validation?

Because in this case it make sense to have separate option to be able to change setting for it. For example turn off/just to have warning for the mentioned errors,  `Definition for rule 'angular/timeout-service' was not found`.

I meant the following use case: 
```
 I would like to use some plugin (for example: `eslint-plugin-angular`)  on local  as ESLint pre-commit hook or whatever. So I would like to ignore these errors until Codeclimate ESlint engine adds support for plugin.
```

**Comment by pbrisbin** [comment]
> Does codeclimate eslint engine have some option to skip this validation?

I understand your usecase and we've attempted some things in that direction, but unfortunately it's difficult to maintain in a long-term way because it requires changes to the underlying eslint codebase itself. So far, we've taken the approach of keeping the limitation in place, but bundling popular plugins to reduce its impact.

I do plan to add angular as a supported plugin, and I apologize it's taking me a little while to get to it.

**Comment by shahulhameedp** [comment]
I think this is working now. It worked for me after updating the codeclimate's eslint in my local by running this command `codeclimate engines:install`

**Comment by dblandin** [comment]
@shahulhameedp Thanks for the bump!

Support for eslint-plugin-angular package rolled out to the eslint-2 channel this past Tuesday and is available now on codeclimate.com or the CLI after updating the engine.
