### ISSUE TITLE
Update eslint-config-airbnb

### ISSUE THREAD

**Issue by lencioni** [codeclimate/codeclimate-eslint#108]
It looks like the package.json file here restricts the eslint-config-airbnb versions after 5.0.0 and before 6.0.0. This configuration is currently on version 9 and will likely soon release version 10. What do you think about updating it here?

**Comment by pbrisbin** [comment]
Hi @lencioni, the master branch of this repository represents the engine's `stable` channel, and is still using ESLint v1, which is why config-airbnb is being held back at that version (we ran into compatibility problems trying to upgrade it without also upgrading ESLint itself).

We also have an `eslint-2` channel, which currently ships v9 of config-airbnb. This will eventually become the `stable` channel, but you can try it out now by adding `channel: eslint-2` to the `engine` block in your `.codeclimate.yml`.

For more details, see here: https://docs.codeclimate.com/docs/engine-channels

**Comment by lencioni** [comment]
Ah, I see. Thanks for the info!

**Comment by lencioni** [comment]
I take it you'll start an `eslint-3` branch and channel soon? ;)
