### ISSUE TITLE
Please support Typescript 3.7

### ISSUE THREAD

**Issue by jackholmes1010** [codeclimate/codeclimate-eslint#476]
Please could somebody add support for Typescript 3.7 for the `eslint-6` channel.

![Screen Shot 2020-01-14 at 5 00 12 PM](https://user-images.githubusercontent.com/3443076/72313176-58049380-36ef-11ea-9860-4874ddb686c5.png)

`typescript`, `@typescript-eslint/eslint-plugin` and `@typescript-eslint/parser` need to be updated.

Thank you!

**Comment by stalniy** [comment]
any progress on this? Currently I need to disable codeclimate as it doesn't play well with `eslint-airbnb-typescript/base`:

![Screenshot from 2020-04-09 08-25-48](https://user-images.githubusercontent.com/1159966/78860820-d006ff00-7a3b-11ea-9fd1-2e62e3406144.png)

This is cannot be fixed by changing code...

![Screenshot from 2020-04-09 08-26-53](https://user-images.githubusercontent.com/1159966/78860851-e319cf00-7a3b-11ea-852d-86ebb333762c.png)

**Comment by octalmage** [comment]
This is causing big issues for us, and is forcing developers to lose confidence in Code Climate and ignore it overall.

**Comment by fede-moya** [comment]
@jackholmes1010 @stalniy @octalmage this should have been addressed by https://github.com/codeclimate/codeclimate-eslint/pull/493 , anyone still experiencing this problem ?

**Comment by claygriffiths** [comment]
We're no longer seeing this error on our end. Thank you!
