### ISSUE TITLE
Update eslint-config-airbnb to v8.0.0

### ISSUE THREAD

**Issue by pbrisbin** [codeclimate/codeclimate-eslint#90]
We install v5.0.0 which comes with `eslint-config-airbnb/base`. They've since deprecated that for `eslint-config-airbnb`. Users moving to the new import error because this engine doesn't have it. I believe updating should be safe since v8.0.0 still includes `/base` and `/legacy` (both deprecated).

/cc @amercier

**Comment by GordonDiggs** [comment]
I tried doing this and ran into some issues around ESLint versions. It seemed like the new version of `eslint-config-airbnb` included rules only available in ESLint 2.

**Comment by dblandin** [comment]
Good news! The new `eslint-2` channel for this engine now comes vendored with `eslint-config-airbnb@9.0.1`.

I just released an update with updated dependencies to both the CLI and [codeclimate.com]().

@amercier, @sonnyt You can find documentation on how to use the new channel on our [docs site](https://docs.codeclimate.com/v1.0/docs/eslint#eslint-2).

**Comment by amercier** [comment]
@dblandin Thanks! I'm now able to make the build run using ESLint 2.x and `eslint-config-airbnb-base` (amercier/npm-package-skeleton#47 for anyone interested in how to configure this). However, I'm having a weird issue: 

![screen shot 2016-05-27 at 2 52 23 pm](https://cloud.githubusercontent.com/assets/1246795/15622108/b1c12d2a-241a-11e6-9f8f-c20a824ece2c.png)

Note: `chai` is in my project's devDependencies, and running `eslint specs/lib/index.spec.js` manually works fine (OK on my machine, OK on Travis CI).

Should I open a separate issue for this?

**Comment by dblandin** [comment]
Looks like there are a few checks enabled by default in [eslint-config-airbnb](https://github.com/airbnb/javascript/blob/c9f6ff36c5ecb994b5ea728ae72384c4d418e68c/packages/eslint-config-airbnb-base/rules/imports.js#L26) from [eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import#rules) that aren't currently supported on [codeclimate.com]() since we don't install project dependencies during an analysis. The same checks should work via [the CLI](https://github.com/codeclimate/codeclimate) if you've run `npm install` locally.

Our inferred configs should be updated to disable those checks so thanks for bring it to our attention!

You can either disable those checks within your `.codeclimate.yml`:

```yaml
engines:
  eslint:
    enabled: true
    channel: "eslint-2"
    checks:
      import/no-unresolved:
        enabled: false
```

or in your ESLint config:

```json
{
  "extends": "airbnb-base",
  "rules": {
    "import/no-unresolved": 0
  }
}
```
